[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "ds-contract"
version = "0.1.0"
description = "CLI skeleton for the ds_contract package"
requires-python = ">=3.11"
authors = [{name = "session-lab", email = "devnull@example.com"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
ds-contract = "ds_contract.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
